### ISSUE TITLE
Create an example JSON document of a FHIR DiagnosticReport that approximates a PFT roughly

### ISSUE THREAD

**Issue by jdjkelly** [Automate-Medical/fhir-pft-profile#1]
# Basic task

Create a JSON document in this repository called PFT-example.json. The JSON should roughly model out what a PFT could look like if it was a [DiagnosticReport](https://www.hl7.org/fhir/diagnosticreport.html#bnc) + [Observations](https://www.hl7.org/fhir/observation.html) in the R4+ version of FHIR.

Use the questions as opportunity to learn more about what could be built in the open around Profiles/Registries and to design next task. The goal here is to quickly define what a PFT could look like in raw JSON by hand.

Start by reading this: https://simplifier.net/guide/profilingacademy/IntroductiontoFHIRandprofiling

## Hints

- Use the basic data definitions from the [PFT standardized report](https://www.thoracic.org/statements/resources/pft/standardized-pulmonary-function-report.pdf)
- See also the type definitions we built for PFT Extractor + PFT Tutorbot, because we defined these on the basis of the PFT standardized report
- See also the LOINC code mappings we built for PFT Extractor - note though that there is a big gap in LOINC codes for PFTs
- https://github.com/Automate-Medical/pft-extractor/blob/master/src/%40types/index.ts
- https://github.com/Automate-Medical/pft-extractor/blob/master/src/server/src/structure/transform.ts#L124
- https://www.atsjournals.org/doi/full/10.1513/AnnalsATS.202010-1318ST

## Questions

- Is this a [Profile](https://www.hl7.org/fhir/profiling.html) or an [ImplementationGuide](https://www.hl7.org/fhir/ImplementationGuide.html)?
- Can we use Forge to do this? (requires windows)
- Are there any other open source projects to generate them?

**Comment by jamais-vu** [comment]
Using the FHIR docs and examples I've created a basic mock-up of what I think a PFT could look like. The mock data is from _Recommendations for a Standardized Pulmonary Function Report_ (DOI: 10.1164/rccm.201710-1981ST).

### Overview

**Basic idea**: create a `Bundle` which has:
- exactly one `DiagnosticReport`, representing the full PFT
- several `Observations`, corresponding to individual measurements, which are referenced in `DiagnosticReport.result`

Let me know if you think I'm on the right track, or I should revise it and try an alternative model.

The example contains only one Observation (FVC pre-bronchodilator) but more can be added after I figure out if this is a promising approach. I'll also ensure it's valid after working out the rough model.

**Further thoughts**:
- Observations can be part of larger events (`Observation.partOf`). We might want to associate Observations with Procedures, (e.g. with Spirometry, or Slow Vital Capacity).
- Observations can have several component Observations (`Observation.component`). Components share the same attributes and are part of a single Observation, but the reference ranges can differ. This might be useful for cases like pre- vs post-bronchodilation, assuming we can also give those Components different codes.
- `partOf` and `component` also mean if we simply create an Observation for each and every specific measurement, we could later determine which share attributes or are part of the same procedure, and then transfer those attributes to their common ancestor.

**TODOs**:
- I'll brainstorm a way to include % predicted and z-score for the tests.
- May also want a way to specify `Observation.referenceRange.low` and `Observation.referenceRange.high` correspond specifically to LLN/ULN.

### Additional Notes
This example assumes we also have the following FHIR resources (listed as `Type`/`id`), but does not implement them:
- Patient/"patient-01"
- Encounter/"encounter-01"
- Practitioner/"practitioner-01"
- Organization/"org-01"

(The comments also mean it's not technically valid JSON. Those will be removed when finished.)

### Example JSON
<details><summary>PFT-example.json (click to expand)</summary>

```JSON
{
  "resourceType": "Bundle",
  "id": "1",
  "type": "collection",
  "entry": [
    {
      "resource": {
        "resourceType": "DiagnosticReport",
        "id": "report-01",
        "status": "final",
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "81458-2",
              "display": "Pulmonary function test panel"
            }
          ],
          "text": "Pulmonary Function Test"
        },
        "subject": {
          "reference": "Patient/patient-01" // TODO: Is Type/id proper form? Or just id?
        },
        "encounter": [
          {
            "reference": "Encounter/encounter-01",
          }
        ],
        "effectiveDateTime": "2017-02-24",
        "performer": [
          {
            "reference": "Practitioner/practitioner-01",
            "display": "Dr. P. Pulmonologist"
          },
          {
            "reference": "Organization/org-01",
            "display": "Sample Pulmonary Function Laboratory"
          },
        ],
        "resultsIntepreter": [
          {
            "reference": "Practitioner/practitioner-01",
            "display": "Dr. P. Pulmonologist"
          },
        ],
        "result": [
          {
            "reference": "Observation/ob-01"
          },
          {
            "reference": "Observation/ob-02"
          },
          // TODO: More `Observations` go here.
        ],
        "conclusion": "Moderately severe, partially reversible airflow obstruction."
        // TODO: How to add in Technician Comments from sample pdf?
        "conclusionCode": [
          // TODO: One or more codes representing conclusion of diagnostic report.
          // Type: `CodeableConcept`
        ],
        "presentedForm": [
          {
            "contentType": "application/pdf",
            "language": "en-US",
            "title": "Example PFT DiagnosticReport"
          }
        ]
      }
    }
    {
      "resource": {
        "resourceType": "Observation",
        "id": "ob-01",
        "status": "final",
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "19876-2",
              "display": "Forced vital capacity [Volume] Respiratory system by Spirometry --pre bronchodilation"
            }
          ],
          "text": "FVC (Forced Vital Capacity) Best, Pre-bronchodilator"
        },
        "subject": {
          "reference": "patient-01"
        },
        "performer": [
          {
            "reference": "Practitioner/practitioner-01",
            "display": "Dr. P. Pulmonologist"
          },
          {
            "reference": "Organization/org-01",
            "display": "Sample Pulmonary Function Laboratory"
          },
        ],
        "valueQuantity": {
          "value": 3.90,
          "unit": "L",
          "system": "metric", // TODO: Think this is incorrect. FHIR says it has type `uri`, where do we reference metric system?
          "code": "L" // TODO: Double-check this.
        },
        "referenceRange": [
          {
            "low": {
              "value": 3.70,
              "unit": "L",
              "system": "metric",
              "code": "L"
            },
          }
        ],
      }
    }
  ]
}
```

</details>

**Comment by jdjkelly** [comment]
> Using the FHIR docs and examples I've created a basic mock-up of what I think a PFT could look like. The mock data is from _Recommendations for a Standardized Pulmonary Function Report_ (DOI: 10.1164/rccm.201710-1981ST).
> 
> ### Overview
> **Basic idea**: create a `Bundle` which has:
> 
> * exactly one `DiagnosticReport`, representing the full PFT
> * several `Observations`, corresponding to individual measurements, which are referenced in `DiagnosticReport.result`
> 
> Let me know if you think I'm on the right track, or I should revise it and try an alternative model.

1:N (DR:O) was my assumption as to how this works, from my own brief read of these types when I was writing this issue. Bundle makes sense too.

By the way, here is a good reference for the intersection of LOINC + PFTs: https://www.pftforum.com/blog/loinc-and-why-it-matters-to-your-his-interface/ - there's an Excel sheet that tries to map out different PFT values to LOINC. Also, in case you haven't figured it out yet or didn't know already SNOMED and IDC10 are other "medical terminologies" or in FHIR terms "CodeableConcepts". SNOMED comes up as a diagnostic code, i.e. the code for COPD. CPT codes are CodeableConcepts too, as a I mentioned, but they refer to specific clinician activities (like a 15 minute patient visit or doing a heart surgery etc). 

> 
> The example contains only one Observation (FVC pre-bronchodilator) but more can be added after I figure out if this is a promising approach. I'll also ensure it's valid after working out the rough model.
> 
> **Further thoughts**:
> 
> * Observations can be part of larger events (`Observation.partOf`). We might want to associate Observations with Procedures, (e.g. with Spirometry, or Slow Vital Capacity).

Very interesting point. 

> * Observations can have several component Observations (`Observation.component`). Components share the same attributes and are part of a single Observation, but the reference ranges can differ. This might be useful for cases like pre- vs post-bronchodilation, assuming we can also give those Components different codes.

Super interesting point - yes, if you look at the ATS standard they are visually connected. Spiro reads on PFTs either have a PRE only or both. If it's unmarked it's assumed to be PRE. If you look at the LOINC structure above, you'll notice that there are different codes for pre and post **and** unmarked. This is one of the problems highlighted here (search "LOINC"): https://www.atsjournals.org/doi/suppl/10.1513/AnnalsATS.202010-1318ST/suppl_file/executive_summary.pdf

I think every time I have structured this - you can look at the previous examples from the other repos (either the GraphQL types in PFT TUtorbot or the TypeScript types in PFT Extractor) - I've made flat maps of values. I haven't tried to say "this is the spirometry observation for FVC and inside of it are both pre and post values", instead I say "this is the FVC pre" and "this is the FVC post" as separate types.

> * `partOf` and `component` also mean if we simply create an Observation for each and every specific measurement, we could later determine which share attributes or are part of the same procedure, and then transfer those attributes to their common ancestor.
> 
> **TODOs**:
> 
> * I'll brainstorm a way to include % predicted and z-score for the tests.

This seems pragmatic, yes.

> * May also want a way to specify `Observation.referenceRange.low` and `Observation.referenceRange.high` correspond specifically to LLN/ULN.

Agree. Is there a Narrative type anywhere where we can add description maybe? If not, I think this is actually fine preliminarily and wouldn't overthink yet.

> 
> ### Additional Notes
> This example assumes we also have the following FHIR resources (listed as `Type`/`id`), but does not implement them:
> 
> * Patient/"patient-01"
> * Encounter/"encounter-01"
> * Practitioner/"practitioner-01"
> * Organization/"org-01"
> 
> (The comments also mean it's not technically valid JSON. Those will be removed when finished.)

Yes, good, please dont model these at all just keep them as References. We should only model references in the case that they are very, very directly related to the PFT data.

> 
> ### Example JSON
> PFT-example.json (click to expand)

-----

The other thing I would mention is that I would focus on just Spirometry and Diffusion/Transfer Capacity results. The Standard PFT has a ton of content in it, but realistically the **median** PFT is just spiro alone and a good one includes DLCO.

**Comment by jdjkelly** [comment]
I forgot to add two other things I wanted to mention. First:

https://simplifier.net/LungCancerDiagnosisComputableCareGuideline

I think this is an ImplementationGuide. Note that Simplifier.net interface is just like GitHub in that you can actually download the raw JSON version of it. Anyways, this is interesting just as a practical reference point for something related, and also as a starting point for understanding how the IG "Registries" work (how you can share and submit IGs and... profiles?)

The second thing: 

https://simplifier.net/PulmonaryfunctionTes

This is... also an IG or a profile? But, importantly, it was someone's previous (draft, solo) attempt at doing this for PFTs. Go to Resources -> and you'll see PFT is a "profile on Diagnostic Report" -> click that. You can explore the profile or download it.

**Comment by jamais-vu** [comment]
Here's a rough example of what I was thinking with `Observation.component`. This is a single `Observation`, with two components for FVC pre and post. 

I'll think more about whether this is the proper approach. From what I understand, Components are not separable, and exist to group Observations for which measurements cannot be understood in isolation (for example, interpretation of blood pressure requires both systolic and diastolic measurements). Since spirometry results sometimes only include FVC pre, we probably want to group them another way.

[Section 10.1.4.3: Observation Grouping](https://www.hl7.org/fhir/observation.html#obsgrouping) has some further discussion of this. If we wish to group the spirometry Observations, I think [`Observation.hasMember`](https://www.hl7.org/fhir/observation-definitions.html#Observation.hasMember) might work. We could create a group of Observations for each test panel: one group for spirometry, one group for plethysmography, and so on. We might also want to define Profiles (I think they'd be Profiles?) for those test panels as well, since PFTs may be composed of various tests. I think groups permit optional members, so they'd be fine for panels where not all members exist (e.g. no FVC post).

For example, the nesting of Resources might look like:
- Level 0: DiagnosticReport (the PFT)
  - Level 1: Groups of Observations representing test panels (not sure what Resource type they would have)
    - Level 2: Maybe groups for same types of measurements over time (e.g. FVC, pre vs post)
      - individual Observations for each measurement

Level 2 might alternatively make sense for collections of different measurements which are repeated across one panel (e.g. a collection of FVC+FEV+FET Resources, which we reuse for pre and post).

My basic idea here is that a PFT has elements which intuitively feel like they should be grouped (primarily the test panels), and grouping them might also permit better reusability/composability/semantics compared to a totally flat PFT model. Does that sound like a tradeoff worth making? Maybe it's not a concern if these are primarily intended to be read by computers.

<details><summary>FVC-observation-component-example.json (click to expand)</summary>

```JSON
{
  "resource": {
    "resourceType": "Observation",
    "id": "ob-01",
    "status": "final",
    "code": {
      "coding": [
        {
          "system": "http://loinc.org",
          "code": "19868-9",
          "display": " Forced vital capacity [Volume] Respiratory system by Spirometry"
        }
      ],
      "text": "FVC Best"
    },
    "subject": {
      "reference": "patient-01"
      "display"
    },
    "performer": [
      {
        "reference": "Practitioner/practitioner-01",
        "display": "Dr. P. Pulmonologist"
      },
      {
        "reference": "Organization/org-01",
        "display": "Sample Pulmonary Function Laboratory"
      },
    ],
   "referenceRange": [
      {
        "low": {
          "value": 3.70,
          "unit": "L",
          "system": "http://unitsofmeasure.org",
          "code": "L"
          },
        "high": {
          "value": 5, // TODO: Placeholder value, not real ULN.
          "unit": "L",
          "system": "http://unitsofmeasure.org",
          "code": "L"
        },
        "type": {
          "text": "FVC (Best) normal bounds"
        }
      }
    ],
   "component": [
      // Component: FVC Best (Pre-bronchodilator)  measurement
      {
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "19876-2",
              "display": "Forced vital capacity [Volume] Respiratory system by Spirometry --pre bronchodilation"
            }
          ],
          "text": "FVC Best (Pre-bronchodilator)"
        },
        "valueQuantity": {
          "value": 3.90,
          "unit": "L",
          "system": "http://unitsofmeasure.org",
          "code": "L"
        },
      },
      // Component: FVC Best (Post-bronchodilator) measurement
      {
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "19874-7",
              "display": "Forced vital capacity [Volume] Respiratory system by Spirometry --post bronchodilation"
            }
          ],
          "text": "FVC Best (Post-bronchodilator)"
        },
        "valueQuantity": {
          "value": 4.70,
          "unit": "L",
          "system": "http://unitsofmeasure.org",
          "code": "L"
        },
      }
    ]
  }
}
```
</details>

I focused a lot on grouping here, so I'll respond to the rest in a separate reply.

**Comment by jamais-vu** [comment]
>By the way, here is a good reference for the intersection of LOINC + PFTs: https://www.pftforum.com/blog/loinc-and-why-it-matters-to-your-his-interface/ - there's an Excel sheet that tries to map out different PFT values to LOINC.

Thanks, this is really useful. I've encountered SNOMED and IC10, and I'll get a grasp of `CodeableConcept`. 

>including z-scores and % pred

I think the best way to include these is as separate Observations, with `Observation.derivedFrom` referencing their relevant Observation. That's because `z-score` and `% pred` are a function of the measured value (which we include as an Observation) and the predicted value (which doesn't seem to be included in most PFTs, but maybe we can link those standards somehow). 

This is might actually be a good use case for the aformentioned `Observation.component` model, since `z-score` and `% pred` don't make sense outside of the context of the Observation they're derived from.

>how to handle LLN/ULN

Forgot to point this out in the Component I just posted, but I changed how I handle `referenceRange`. Instead of having single bound for LLN and saying it's the "high" bound, I use LLN/ULN to create a `referenceRange` we consider "normal", and then use LLN/ULN as its lower and upper bounds. So the lower/upper bound is implicitly the lower/upper limit of normal, and maybe we can explicitly specify this in a satisfactory way.

This might be a problem in cases where only one bound is provided - we don't necessarily want to say everything above that is normal, since a huge result might be abnormal.

>Is there a Narrative type anywhere where we can add description [of LLN/ULN] maybe? 

I think this could work but I'd have to look more into it. 

Side note: Looking into `Narrative` also brought me to [`Composition`](https://www.hl7.org/fhir/composition.html) . This might be a good idea for the PFT model - a PFT report sounds like the sort of document for which this type is intended. Sections of the Composition could refer to separate Procedures, each of which could have a Narrative.

> I forgot to add two other things I wanted to mention. First:
> 
> https://simplifier.net/LungCancerDiagnosisComputableCareGuideline
> 
> I think this is an ImplementationGuide. Note that Simplifier.net interface is just like GitHub in that you can actually download the raw JSON version of it. Anyways, this is interesting just as a practical reference point for something related, and also as a starting point for understanding how the IG "Registries" work (how you can share and submit IGs and... profiles?)
> 
> The second thing:
> 
> https://simplifier.net/PulmonaryfunctionTes
> 
> This is... also an IG or a profile? But, importantly, it was someone's previous (draft, solo) attempt at doing this for PFTs. Go to Resources -> and you'll see PFT is a "profile on Diagnostic Report" -> click that. You can explore the profile or download it.

These look promising but I'll need some more time to fully understand them. Will let you know my thoughts.

**Comment by jdjkelly** [comment]
@jamais-vu I've enabled write/commit access to this repository by the way, so if you follow the setup instructions in the root of the project you should have a clonable/pushable repo locally.

> Forgot to point this out in the Component I just posted

Not sure what you are referring to here - the original JSON preview in your comment? Did you update it or?

I think today would be a good opportunity to push existing JSON/updated sample into the repo directly on a branch and open a PR against master.  That way we can take some of the initial thinking here and get really specific (we can comment in line on the code etc).

- [ ] Get repo working locally
- [ ] Push existing DiagnosticReport + Observations + rough scratch work into new branch

You can solve for the valid JSON thing btw just by changing the file type to .js/ts and doing `const example = { ... }` - then all of the comments are valid because it's not a JSON file it's a js program that assigns an object to a const.

> I think the best way to include these is as separate Observations, with Observation.derivedFrom referencing their relevant Observation. That's because z-score and % pred are a function of the measured value (which we include as an Observation) and the predicted value (which doesn't seem to be included in most PFTs, but maybe we can link those standards somehow).

I really like this. I think depth on this is good with a single sample i.e. keep using FVC pre, and basically see what a complete DiagnosticReport resource with FVC pre in litres and all of the derived observations and reference values along side it. That would be a good checkpoint.

> Side note: Looking into Narrative also brought me to Composition . This might be a good idea for the PFT model - a PFT report sounds like the sort of document for which this type is intended. Sections of the Composition could refer to separate Procedures, each of which could have a Narrative.

Interesting - especially because I think this relates to the Providence stuff (you can sign documents?). This is a "backlog" label to me (backlog is anything that's just not the current focus but good context/idea/good to remember).

**Comment by jamais-vu** [comment]
Ah, my mistake, I pushed directly to master. Should I revert this, or add a new branch moving forward?

>Not sure what you are referring to here - the original JSON preview in your comment? Did you update it or?

In my [previous reply](https://github.com/Automate-Medical/fhir-pft-profile/issues/1#issuecomment-850068847) I had included an example of an Observation with Components, but it's inside a collapsible element and isn't very visible in the reply. But it's the same JSON as in the `FVC-observation-component-example.js` file I've just committed.

>You can solve for the valid JSON thing btw just by changing the file type to .js/ts and doing `const example = { ... }`

Thanks, this works, Github highlighting the comments didn't look pretty.

>I think depth on this is good with a single sample i.e. keep using FVC pre, and basically see what a complete DiagnosticReport resource with FVC pre in litres and all of the derived observations and reference values along side it. That would be a good checkpoint.

Good to hear, I'll create an example and we can see how that looks.

>Interesting - especially because I think this relates to the Providence stuff (you can sign documents?). 

Providence doesn't sound familiar to me - did you mean the [`Provenance`](https://www.hl7.org/fhir/provenance.html) resource?  Provenance itself looks relevant, I'll see where it might fit in.

**Comment by jdjkelly** [comment]
We discussed in person today the state of this issue. We decided that we would:

- [x] Add the type definitions to the project just to make it easier
- [x] Validate that the existing work-to-date doesn't have type problems at least as far as the existing definitions are concerned
- [x] This requires setting up a node project with npm + install typescript
- [ ] Split Diagnostic Report into two variants - one where status is preliminary and the other where it is final - the difference between them being the presence or absence of narrative by the pulmonologist vs. just the respiratory therapist or no one at all
- [x] Add FVC, FEV1, FEV1/FVC as three independent "categories" of values (the result itself, the reference value (LLN), the zscore, ... etc, "derivedFrom") 
- [x] Do the above for both pre and post-bronchodilator samples

**Comment by jdjkelly** [comment]
Closing this, since we're tracking work elsewhere now.
